# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_clarabel_wrappers", use_symbols = TRUE, package_name = "clarabel")

#' @usage NULL
#' @useDynLib clarabel, .registration = TRUE
NULL

clarabel_solve <- function(m, n, Ai, Ap, Ax, b, q, Pi, Pp, Px, cone_spec, r_settings) .Call(wrap__clarabel_solve, m, n, Ai, Ap, Ax, b, q, Pi, Pp, Px, cone_spec, r_settings)


# nolint end
